name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 14.x
      - run: cd ./frontend && yarn install
      - run: make frontend-build
      - uses: actions/upload-artifact@master
        with:
          name: js-bundle
          path: frontend/static/frontend/main.js
  api:
    needs: frontend
    runs-on: ubuntu-18.04
    container:
      image: node:14.4
      options: --network-alias testHost
    env:
      NODE_ENV: test
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-firefox:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.0.10
      - name: View poetry --help
        run: poetry --help
      - name: Install Dependencies
        run: poetry install
      - run: make test
        env:
          SECRET_KEY: test-key
          WEBDRIVER_HOST: http://hub:4444/wd/hub