name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 14.x
      - run: cd ./frontend && yarn install
      - run: make frontend-build
      - uses: actions/upload-artifact@master
        with:
          name: js-bundle
          path: frontend/static/frontend/main.js
  api:
    needs: frontend
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.0.10
      - name: View poetry --help
        run: poetry --help
      - name: Install Dependencies
        run: poetry install
      - run: make test
        env:
          SECRET_KEY: test-key