# Generated by Django 3.1 on 2020-08-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='repo',
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.URLField(default='https://github.com'),
        ),
        migrations.AddField(
            model_name='project',
            name='view',
            field=models.URLField(default='https://github.com'),
        ),
    ]
