# Generated by Django 3.1 on 2020-08-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_add_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvitem',
            name='icon',
            field=models.CharField(default='FaBookmark', max_length=20),
            preserve_default=False,
        ),
    ]
