# Generated by Django 3.1 on 2020-08-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_add_types'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemType',
            new_name='ItemCategory',
        ),
    ]
