# Generated by Django 3.1 on 2020-08-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_cvitem_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvitem',
            name='link',
            field=models.URLField(null=True, blank=True),
        ),
    ]
